services:
  jenkins:
    container_name: jenkins
    restart: always
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    volumes:
      - jenkins-home:/var/jenkins_home
      - PetProject:/var/jenkins_home/jobs/PetProject

volumes:
  jenkins-home: